// Generated Vulkan API bindings.
// Vulkan and the Vulkan logo are registered trademarks of the Khronos Group Inc.
// 
// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.
// 

// WARNING: This file has automatically been generated on Sat, 10 Jan 2026 23:42:17 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

unsigned int PFN_vkDebugReportCallbackEXT_c918aac4(unsigned int flags, VkDebugReportObjectTypeEXT objectType, unsigned long int object, unsigned long int location, int messageCode, char* pLayerPrefix, char* pMessage, void* pUserData) {
	return debugReportCallbackFuncC918AAC4(flags, objectType, object, location, messageCode, pLayerPrefix, pMessage, pUserData);
}

void PFN_vkDeviceMemoryReportCallbackEXT_e34d104c(VkDeviceMemoryReportCallbackDataEXT* pCallbackData, void* pUserData) {
	deviceMemoryReportCallbackFuncE34D104C(pCallbackData, pUserData);
}

