// Generated Vulkan API bindings.
// Vulkan and the Vulkan logo are registered trademarks of the Khronos Group Inc.
//
// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.
//

// WARNING: This file has automatically been generated on Sat, 31 Jan 2026 19:43:51 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package vulkan provides Go bindings for Vulkan API with support for:
- Core Vulkan 1.0-1.3 functionality
- Dynamic rendering extensions (VK_KHR_dynamic_rendering)
- Physical device features and properties version 2
- Platform-independent API for graphics and compute
*/
package vulkan
