// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vulkan

const (
	GoVersion   = "v1.0.14"
	GitCommit   = "bfa9037"          // the commit JUST BEFORE the release
	VersionDate = "2026-01-31 16:44" // UTC
)
