// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vulkan

const (
	GoVersion   = "v1.0.9"
	GitCommit   = "3bcdb9b"          // the commit JUST BEFORE the release
	VersionDate = "2026-01-05 13:27" // UTC
)
